using Test
using Crystalline
using Crystalline: constant

# Bilbao's tabulated EBRs, used here as an independent reference (see the file for details)
if !isdefined(@__MODULE__, :BilbaoBandReps)
    include("bilbao_bandreps.jl")
end
using .BilbaoBandReps

_bandreps_int_dim(sgnum::Int, D::Int, spinful::Val) =
            bandreps(sgnum, D; spinful) # dimension not a compile-time constant

@testset "bandreps" begin

# defines `is_exceptional_br` to check if a BR induced by a maximal Wyckoff position is an
# "exceptional" BR, i.e., is in fact not an elementary BR (EBR)
# include("ebr_exceptions.jl")
# TODO: currently unused - figure out if we need it or not & keep/delete accordingly

# ---------------------------------------------------------------------------------------- #

@testset "2D: `bandreps` vs. (tabulated) Bilbao EBRs" begin
    # test that Bilbao's tabulated EBRs agree with `bandreps` in 2D (the former are
    # generated by the latter; basically check that the tabulated data is up-to-date)
    for sgnum in 1:17
        for timereversal in (false, true)
            @test convert.(BilbaoBandRep,
                           bandreps(sgnum, Val(2); timereversal, allpaths = false)) ==
                  bilbao_bandreps(sgnum, 2; timereversal, allpaths = false)
        end
    end
end

# a co-rep label up to the order of its parts (e.g., "Γ₁₂ˢΓ₉ˢ" ~ "Γ₉ˢΓ₁₂ˢ"): Bilbao usually,
# but not always, lists the parts of a double-valued co-rep in ascending order, as `realify`
# does
function _unordered_label(l)
    return join(sort([m.match for m in eachmatch(r"[^₀-₉⁺⁻ˢ]+[₀-₉]+[⁺⁻]?ˢ?", l)]))
end

# Wyckoff positions where our labels of the 1D double-valued site irreps ¹Xˢ and ²Xˢ are
# swapped relative to Bilbao's (without time-reversal): as for the 222, mmm, and mm2 site
# symmetries below, the assignment is ambiguous, here because matching a site group to its
# isomorphic point group involves a choice of sign for each operation
# (see `Crystalline._lift_signs`)
SPINFUL_EBR_LABEL_SWAPS = Set([(210, "16c"), (210, "16d"), (212, "4a"), (212, "4b"),
                               (213, "4a"), (213, "4b"), (227, "16c"), (227, "16d")])

@testset "3D: every reference EBR must have a match in a calculated BR" begin
    debug = false
    error_counts = Dict{String, Int}()
    for sgnum in 1:230, spinful in (false, true)
        had_sg_error = false
        for timereversal in (false, true)
            had_tr_error = false

            _brsᶜ = bandreps(sgnum, Val(3); spinful, timereversal, allpaths = false)
            brsᶜ = convert(BilbaoBandRepSet, _brsᶜ)
            brsʳ = bilbao_bandreps(sgnum, 3; spinful, timereversal, allpaths = false)
                      
            # find a permutation of the irreps in `brsʳ` that matches `brsᶜ`'s sorting, s.t.
            # `brsʳ.irlabs[irʳ²ᶜ_perm] == brsᶜ.irlabs`
            irlabsʳ = _unordered_label.(brsʳ.irlabs)
            irʳ²ᶜ_perm = [something(findfirst(==(_unordered_label(irᶜ)), irlabsʳ))
                          for irᶜ in brsᶜ.irlabs]
            append!(irʳ²ᶜ_perm, length(brsᶜ.irlabs)+1) # append occupation number

            seen_wp = Dict{String, Bool}()
            for brʳ in brsʳ
                wpʳ = brʳ.wyckpos
                idx = findfirst(brᶜ -> brᶜ.wyckpos == wpʳ && brᶜ.label == brʳ.label, brsᶜ)
                haskey(seen_wp, wpʳ) || (seen_wp[wpʳ] = false)
                if isnothing(idx)
                    # this can sometimes happen spuriously because Bilbao (i.e. `brsʳ`)
                    # lists the EBRs with unabbreviated Mulliken labels (e.g., A₁ rather 
                    # than A or ¹E²E rather than E) even when it is possible to abbreviate
                    # unambiguously (what `mulliken` does and what `brsᶜ` consequently
                    # references); we account for that by doing a subsequent, slighly looser
                    # check (below)
                    idx = findfirst(brsᶜ) do brᶜ
                        brʳ.wyckpos == brᶜ.wyckpos || return false
                        labʳ = replace(brʳ.label, "↑G"=>"") 
                        labᶜ = replace(brᶜ.label, "↑G"=>"")
                        length(labᶜ) == 1 && only(labᶜ) == first(labʳ) && return true # e.g., A ~ A₁
                        cs = collect(replace(labʳ, "¹"=>"", "²"=>"")) # e.g., ¹E²E ~ E and
                        n = length(cs)                                # ¹E₂ˢ²E₂ˢ ~ E₂ˢ
                        labʳ′ = iseven(n) && cs[1:n÷2] == cs[n÷2+1:end] ?
                                    String(cs[1:n÷2]) : String(cs)
                        labʳ′ == labᶜ && return true
                    end
                end
                
                @test idx !== nothing # test that an associated BR exists in brsʳ (it must)
                idx = something(idx)

                # there are a number of cases where it is impossible to test uniquely
                # against Bilbao, because the assignment of irrep label to the site symmetry
                # group is ambiguous (e.g., for site groups isomorphic to 222; but also for 
                # mmm and mm2): in this case, the assignment of irreps depends on a choice
                # of coordinate system, which we cannot be uniquely determined but
                # so, for these cases, we cannot do a one-to-one comparison (but we can at
                # least test whether the reference Bilbao vector occurs in the set of
                # computed band representation vectors)
                ambiguous = if spinful
                    !timereversal && (sgnum, wpʳ) ∈ SPINFUL_EBR_LABEL_SWAPS &&
                        first(brʳ.label) ∈ ('¹', '²')
                else
                    brʳ.sitesym ∈ ("222", "mmm", "mm2")
                end
                if !ambiguous
                    brᶜ = brsᶜ[idx]
                    @test Vector(brᶜ) == brʳ[irʳ²ᶜ_perm]
                    @test dim(brᶜ) == dim(brʳ)
                else
                    # simply test that the reference Bilbao _vector_ is in the set of
                    # computed EBRs
                    @test brʳ[irʳ²ᶜ_perm] ∈ Vector.(brsᶜ)
                    continue
                end
                
                if debug
                    brᶜ = brsᶜ[idx]
                    if !(Vector(brᶜ) == brʳ[irʳ²ᶜ_perm])
                        had_sg_error || (print("sgnum = $sgnum\n"); had_sg_error = true)
                        had_tr_error || (println("  timereversal = $timereversal"); had_tr_error = true)
                        if !seen_wp[wpʳ]
                            print("    site = $wpʳ (")
                            printstyled("$(brʳ.sitesym)"; color=:yellow)
                            println(")")
                            seen_wp[wpʳ] = true
                        end
                        println("      $(replace(brʳ.label, "↑G"=>""))")
                        brʳ′ = deepcopy(brʳ)
                        brʳ′.irvec .= brʳ.irvec[irʳ²ᶜ_perm[1:end-1]]
                        brʳ′.irlabs .= brʳ.irlabs[irʳ²ᶜ_perm[1:end-1]]
                        println("        ref  = $brʳ′")
                        println("        calc = $brᶜ")
                        if haskey(error_counts, brʳ.sitesym)
                            error_counts[brʳ.sitesym] += 1
                        else
                            error_counts[brʳ.sitesym] = 1
                        end
                    end
                end
            end
        end
        debug && had_sg_error && println()
    end
end

@testset "Plane groups vs. parent space groups" begin
    for (sgnum²ᴰ, sgnum³ᴰ) in enumerate(Crystalline.PLANE2SPACE_NUMS)
        for timereversal in (false, true)
            brs²ᴰ = bilbao_bandreps(sgnum²ᴰ, 2; timereversal, allpaths = false)
            brs³ᴰ = bilbao_bandreps(sgnum³ᴰ, 3; timereversal, allpaths = false)

            # dimensions
            @test sort!(dim.(brs²ᴰ)) == sort!(dim.(brs³ᴰ))

            # topological classification
            @test indicator_group_as_string(stack(brs²ᴰ)) ==
                  indicator_group_as_string(stack(brs³ᴰ))
        end
    end
end

@testset "Orbits of bandrep site groups are all in parallelepid primitive unit cell" begin
    # check that the constant part of every orbit position of a bandrep site group lies
    # in the primitive unit cell parallelepiped, in i.e., [0, 1)ᴰ
    for D in 1:3
        for sgnum in 1:MAX_SGNUM[D]
            brs = bandreps(sgnum, Val(D); timereversal = true, allpaths = false)
            cntr = centering(sgnum, D)
            for br in brs
                siteg = group(br)
                rs = orbit(siteg)            # conventional setting
                rs′ = primitivize.(rs, cntr) # primitive setting

                # check that the constant part of `r`'s coordinates lie in [0,1)
                @test all(rs′) do r′
                    all(x -> 0 ≤ x < 1, constant(r′))
                end

                # test that we get the same by just primitivizing the site group directly
                siteg′ = primitivize(siteg)
                rs′′ = orbit(siteg′) # primitive setting
                @test all(((r′′, r′),) -> r′′ ≈ r′, zip(rs′′, rs′))

                # also test that operations of primitivized site group "conventionalize" to
                # exactly those of the unprimitivized site group
                siteg′_ops_c = conventionalize.(operations(siteg′), cntr, #= modw =# false)
                @test operations(siteg) ≈ siteg′_ops_c
            end
        end
    end
end


@testset "`explicitly_real = true` vs. `explicitly_real = false`" begin
    for sgnum in 1:MAX_SGNUM[3]
        brs  = bandreps(sgnum, Val(3); timereversal = true, explicitly_real = false)
        pbrs = bandreps(sgnum, Val(3); timereversal = true, explicitly_real = true)
        @test all(zip(brs, pbrs)) do (br, pbr)
            br.n == pbr.n # symmetry vectors should be the same regardless
        end
        for pbr in pbrs
            b = all(x -> x ≈ real(x), pbr.siteir.matrices) # D ≈ Re(D)
            if !b
                println(sgnum, ": ", pbr)
            end
        end
    end
end

@testset "stack(::Collection{<:BandRep})" begin
    brs = bandreps(2, Val(3); timereversal=false)
    @test stack(brs) == invoke(stack, Tuple{AbstractVector{<:AbstractVector}}, brs)
end

@testset "`include_nonmaximal` kwarg" begin
    # space group 147
    brs_max = bandreps(147, Val(3))
    brs_incl_nonmax = bandreps(147, Val(3); include_nonmaximal = true) # all BRs, maximal or nonmaximal
    wps_incl_nonmax = wyckoffs(147, Val(3)) # all Wyckoff positions, maximal or nonmaximal
    sort!(wps_incl_nonmax; by=string) # for stable selection and comparison below
    wps_max = wps_incl_nonmax[[1,2,4,5,6]] # 1a, 1b, 2d, 3e, 3f
    @test wps_max == sort(unique(position.(brs_max)); by=string)
    @test wps_incl_nonmax == sort(unique(position.(brs_incl_nonmax)); by=string)
    @test length(wps_incl_nonmax) > length(wps_max)

    # space group 2
    brs_max = bandreps(2, Val(3))
    brs_incl_nonmax = bandreps(2, Val(3); include_nonmaximal=true)
    @test length(brs_max) == 16
    @test length(brs_incl_nonmax) == 17
    @test "2i: [α, β, γ]" ∉ string.(unique(position.(brs_max)))
    @test "2i: [α, β, γ]" ∈ string.(unique(position.(brs_incl_nonmax)))
end

@testset "Inferred irrep types" begin
    # a `Val` dimension infers concretely; a plain `Integer` dimension cannot, but `spinful`
    # must still fix the irrep types on its own (it is only kept across an unknown dimension
    # because `Crystalline._bandrep_type` picks them by dispatch rather than by a value)
    @test @inferred(bandreps(2, Val(3))) isa
                Collection{BandRep{3, LGIrrep{3}, SiteIrrep{3}}}
    T  = only(Base.return_types(_bandreps_int_dim, (Int, Int, Val{false})))
    Tᵈ = only(Base.return_types(_bandreps_int_dim, (Int, Int, Val{true})))
    @test T  <: Collection{<:BandRep{<:Any, <:LGIrrep,  <:SiteIrrep}}
    @test Tᵈ <: Collection{<:BandRep{<:Any, <:DLGIrrep, <:DSiteIrrep}}
end
end # @testset "bandreps"