"""
    generators(num::Integer, T::Type{<:AbstractGroup{D}}[, optargs])
    generators(pgiuc::String, T::Type{<:AbstractPointGroup{D}}) -->  Vector{<:AbstractOperation{D}}

Return the generators of the group type `T` which may be an `AbstractSpaceGroup{D}` or
`AbstractPointGroup{D}` parameterized by its dimensionality `D`. Depending on `T`, the group
is determined by inputting as the first argument:

- `SpaceGroup{D}` or `DSpaceGroup{D}`: the space group number `num::Integer`.
- `PointGroup{D}` or `DPointGroup{D}`: the point group IUC label `pgiuc::String` (see also
  [`pointgroup(::String)`](@ref)) or the canonical point group number `num::Integer`, which can
  optionally be supplemented by an integer-valued setting choice `setting::Integer` (see
  also [`pointgroup(::Integer, ::Integer, ::Integer)`](@ref)).
- `SubperiodicGroup{D}`: the subperiodic group number `num::Integer`.

For double groups, `DSpaceGroup{3}` and `DPointGroup{3}`, the returned generators are
`DSymOperation`s, with the barred identity ``\\bar{E}`` as a final generator.

Setting choices match those in [`spacegroup`](@ref), [`pointgroup`](@ref), and
[`subperiodicgroup`](@ref).

Iterated composition of the returned symmetry operations will generate all operations of the
associated space or point group (see [`generate`](@ref)).
As an example, `generate(generators(num, `SpaceGroup{D}))` and `spacegroup(num, D)` return
identical operations (with different sorting typically); and similarly so for point and
subperiodic groups.

## Example

Generators of space group 200:
```jldoctest
julia> generators(200, SpaceGroup{3})
4-element Vector{SymOperation{3}}:
 2₀₀₁
 2₀₁₀
 3₁₁₁⁺
 -1
```

Generators of point group m-3m:
```jldoctest
julia> generators("2/m", PointGroup{3})
2-element Vector{SymOperation{3}}:
 2₀₁₀
 -1
```

Generators of the Frieze group 𝓅2mg:
```jldoctest
julia> generators(7, SubperiodicGroup{2, 1})
2-element Vector{SymOperation{2}}:
 2
 {m₁₀|½,0}
```

## Citing

Please cite the original data sources if used in published work:

- Space groups:
  [Aroyo et al., Z. Kristallogr. Cryst. Mater. **221**, 15
  (2006)](https://doi.org/10.1524/zkri.2006.221.1.15);
- Point group: Bilbao Crystallographic Server's
  [2D and 3D GENPOS](https://cryst.ehu.es/cryst/get_point_genpos.html);
- Subperiodic groups: Bilbao Crystallographic Server's
  [SUBPERIODIC GENPOS](https://cryst.ehu.es/subperiodic/get_sub_gen.html).

## Extended help

Note that the returned generators are not guaranteed to be the smallest possible set of
generators; i.e., there may exist other generators with fewer elements (an example is space
group 168 (P6), for which the returned generators are `[2₀₀₁, 3₀₀₁⁺]` even though the group
could be generated by just `[6₀₀₁⁺]`).
The returned generators, additionally, are not guaranteed to be
[minimal](https://en.wikipedia.org/wiki/Generating_set_of_a_module), i.e., they may include
proper subsets that generate the group themselves (e.g., in space group 75 (P4), the
returned generators are `[2₀₀₁, 4₀₀₁⁺]` although the subset `[4₀₀₁⁺]` is sufficient to
generate the group).
The motivation for this is to expose as similar generators as possible for similar crystal
systems (see e.g. Section 8.3.5 of the International Tables of Crystallography, Vol. A,
Ed. 5 (ITA) for further background).

Note also that, contrary to conventions in ITA, the identity operation is excluded among the
returned generators (except in space group 1) since it composes trivially and adds no
additional context.
"""
function generators(
    sgnum::Integer,
    ::Type{T}
) where {D, T <: AbstractSpaceGroup{D}}
    S = isspinful(T)
    S && (D == 3 || _only_3d(D))
    @boundscheck _check_valid_sgnum_and_dim(sgnum, D)
    codes = SG_GENS_CODES_Vs[D][sgnum]
    hexagonal = S ? _ishexagonal(sgnum, Val(D)) : false # only relevant for spinful

    # convert `codes` to `SymOperation`s and add to `operations`
    operations = Vector{eltype(T)}(undef, length(codes) + S) # extra slot for Ē if spinful
    _include_symops_from_codes!(operations, codes; add_identity=false, hexagonal)
    S && (operations[end] = DSymOperation{D}(one(SymOperation{D}), -one(SU2))) # add on Ē

    return operations
end

# NB: The method below exists separately, rather than putting `::Type{T} = SpaceGroup{3}` in
#     the signature above, because Julia otherwise warns about an unused `D` parameter in
#     the method signature, due to the automatically generated `generators(sgnum)` method.
generators(sgnum::Integer) = generators(sgnum, SpaceGroup{3})

# TODO: remove once `generators(::Integer, ::Type{<:MSpaceGroup})` is implemented
generators(::Integer, ::Type{<:MSpaceGroup}) = error("`generators` is not yet implemented for magnetic space groups")
